version: "3.9"

services:
  redirecter:
    image: tilla1145/redirecter:latest
    container_name: redirecter
    depends_on:
      - database
    volumes:
      - .:/app
    ports:
    - "8090:8090"
    restart: always
    networks:
      - redirect

  database:
    container_name: database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data 
    networks:
      - redirect

networks:
  redirect:
    name: redirect
volumes:
  db: