version: "3.9"

services:
  redirecter:
    build: .
    container_name: redirecter
    depends_on:
      - database
    volumes:
      - .:/app
    ports:
    - "8090:8090"

  database:
    container_name: database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db: