name: Docker build

on:
  push:
    branches-ignore:
      - master
jobs:
  build:
   runs-on: ubuntu-latest
  
   steps:
     - uses: actions/checkout@v3
     - name: Build Docker image 
       run: docker-compose up --build
